version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR....
      - aws --version
      #- $(aws ecr get-login --region ap-south-1 --no-include-email)
      - aws ecr get-login-password --region ap-northeast-3 | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.ap-northeast-3.amazonaws.com
      - # Replace with this to your repository URI
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.ap-northeast-3.amazonaws.com/$REPO_NAME
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $REPO_NAME:latest .
      - docker tag $REPO_NAME:latest $REPOSITORY_URI:latest
      - docker tag $REPO_NAME:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo pushing to AWS repo
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"image-name","imageUri":"%s"}]' $REPOSITORY_URI:latest > imagedefinitions.json 
artifacts:
  files:
    - imagedefinitions.json
    - appspec.yml
    - scripts/install_dependencies.sh
    - scripts/start_server.sh
    - scripts/stop_server.sh
